name: Snake Game

on:
  schedule: # execute every 5 hours
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update Data and Run Snake Game
    runs-on: ubuntu-latest
    
    steps:
      # Generate Snake Animation
      - name: Generate Snake Animation
        id: snake-gif
        uses: Platane/snk@master
        with:
          github_user_name: gholiveira96
          svg_out_path: dist/github-contribution-grid-snake.svg
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
